---
sidebar: sidebar 
permalink: concept-kubernetes.html 
keywords: kubernetes, k8s, back up kubernetes, back up k8s, discover kubernetes cluster, discover k8s, amazon eks, eks, azure, aks, back up persistent volumes, persistent volumes, kubernetes support 
summary: Astra Trident は、ネットアップが管理している、完全にサポートされているオープンソースプロジェクトです。Kubernetes と Persistent Volume フレームワークとネイティブに統合されている Astra Trident は、ネットアップストレージプラットフォームを任意に組み合わせて実行されているシステムから、ボリュームのプロビジョニングと管理をシームレスに行います。 
---
= Cloud Manager での Kubernetes によるデータ管理
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Astra Trident は、ネットアップが管理している、完全にサポートされているオープンソースプロジェクトです。Kubernetes と Persistent Volume フレームワークとネイティブに統合されている Astra Trident は、ネットアップストレージプラットフォームを任意に組み合わせて実行されているシステムから、ボリュームのプロビジョニングと管理をシームレスに行います。 link:https://docs.netapp.com/us-en/trident/index.html["Trident の詳細をご確認ください"^]。



== の機能

Kubernetes クラスタは、 Cloud Manager を使用して直接管理できます。

* Astra Trident をインストール
* ハイブリッドクラウドインフラの一部としてクラスタを追加、管理
* ストレージクラスを追加して管理し、作業環境に接続する。
* Cloud Backup Service を使用して永続ボリュームをバックアップする。




== サポートされる Kubernetes 環境

Cloud Manager は、で実行されるマネージド Kubernetes クラスタをサポートします。

* link:/requirements/kubernetes-reqs-aws.html["Amazon Elastic Kubernetes Service （ Amazon EKS ）"]
* link:/requirements/kubernetes-reqs-aks.html["Microsoft Azure Kubernetes Service （ AKS ）"]
* link:/requirements/kubernetes-reqs-gke.html["Google Kubernetes Engine （ GKE ）"]




== サポートされている Astra Trident 環境

最新バージョンの 4 つの Astra Trident が必要です。Trident は Cloud Manager から直接インストールできます。お勧めします link:https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html["前提条件を確認します"^] インストールの前に、

Astra Trident をアップグレードするには、 link:https://docs.netapp.com/us-en/trident/trident-managing-k8s/upgrade-operator.html["オペレータにアップグレードしてください"^]。



== サポートされるバックエンドストレージ

ネットアップの Astra Trident は各 Kubernetes クラスタにインストールする必要があり、 Cloud Volumes ONTAP はクラスタのバックエンドストレージとして設定する必要があります。



== コスト

Cloud Manager で Kubernetes クラスタを検出する際に料金は発生しませんが、 Cloud Backup Service を使用して永続ボリュームをバックアップした場合に料金が発生します。
