---
sidebar: sidebar 
permalink: concept-kubernetes.html 
keywords: kubernetes, k8s, back up kubernetes, back up k8s, discover kubernetes cluster, discover k8s, amazon eks, eks, azure, aks, back up persistent volumes, persistent volumes, kubernetes support 
summary: Astra Trident は、ネットアップが管理している、完全にサポートされているオープンソースプロジェクトです。Kubernetes と Persistent Volume フレームワークとネイティブに統合されている Astra Trident は、ネットアップストレージプラットフォームを任意に組み合わせて実行されているシステムから、ボリュームのプロビジョニングと管理をシームレスに行います。 
---
= Cloud Manager での Kubernetes によるデータ管理
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Astra Trident は、ネットアップが管理している、完全にサポートされているオープンソースプロジェクトです。Kubernetes と Persistent Volume フレームワークとネイティブに統合されている Astra Trident は、ネットアップストレージプラットフォームを任意に組み合わせて実行されているシステムから、ボリュームのプロビジョニングと管理をシームレスに行います。 link:https://docs.netapp.com/us-en/trident/index.html["Trident の詳細をご確認ください"^]。



== の機能

Tridentのオペレータが、互換性のあるバージョンのAstra Tridentを使用して導入した場合、Cloud Managerを使用してKubernetesクラスタを直接管理できます。

* Astra Tridentのインストールまたはアップグレード
* ハイブリッドクラウドインフラの一部としてクラスタを追加、管理
* ストレージクラスを追加して管理し、作業環境に接続する。
* Cloud Backup Service を使用して永続ボリュームをバックアップする。




== サポートされる Kubernetes 環境

Cloud Manager は、で実行されるマネージド Kubernetes クラスタをサポートします。

* link:./requirements/kubernetes-reqs-aws.html["Amazon Elastic Kubernetes Service （ Amazon EKS ）"]
* link:./requirements/kubernetes-reqs-aks.html["Microsoft Azure Kubernetes Service （ AKS ）"]
* link:./requirements/kubernetes-reqs-gke.html["Google Kubernetes Engine （ GKE ）"]




== サポートされている Astra Trident 環境

Astra Tridentの4つの最新バージョンのうちの1つ link:https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-operator.html["Tridentオペレータを使用して導入されています"^] は必須です。

最新バージョンのAstra Tridentは、Cloud Managerから直接インストールまたはアップグレードできます。

link:https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html["Astra Tridentの前提条件を確認"^]



== サポートされるバックエンドストレージ

NetApp Astra Tridentは各Kubernetesクラスタにインストールする必要があります。また、Cloud Volumes ONTAP またはAmazon FSX for ONTAP は、クラスタのバックエンドストレージとして設定する必要があります。



== コスト

Cloud Manager で Kubernetes クラスタを検出する際に料金は発生しませんが、 Cloud Backup Service を使用して永続ボリュームをバックアップした場合に料金が発生します。
